build:
  allowed:
    - "pull_request.opened"
    - "pull_request.synchronize"
    - "pull_request.reopened"
    - "push"
    - "tag"
  ref_match: "invalid-refs-should-not-work"
  dependencies: []
  routes: []
  maxRunTime: 3600
  docker_image: "ubuntu:14.04"
  system_setup:
    >
      true
  system_config:
    >
      true
  scripts:
    build: ''
    package: ''
  args:
    tests_cmdline: ''
  test_model_task: ''
  cache:
    url: ''
    namespace: ''
