system:
  username: 'build-user'
  homedir:
    linux: '/home/build-user'
    win: '/c/builds/tc-workdir'
  system_setup:
    linux:
      >
        apt-get -qq update &&
        apt-get -qq -y install wget &&
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB &&
        apt-get -qq -y install apt-transport-https &&
        apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB &&
        echo -e "deb https://apt.repos.intel.com/mkl all main" > /etc/apt/sources.list.d/intel-mkl.list &&
        apt-get -qq update &&
        apt-get -qq -y install -y intel-mkl-64bit-2018.2-046 &&
        apt-get -qq -y install autoconf automake &&
        wget https://github.com/Kitware/CMake/releases/download/v3.12.2/cmake-3.12.2-Linux-x86_64.sh &&
        chmod +x cmake-3.12.2-Linux-x86_64.sh &&
        ./cmake-3.12.2-Linux-x86_64.sh --skip-license --prefix=/usr/local &&
        apt-get -qq -y install g++ git libev++-dev libssl-dev libboost-all-dev libtool &&
        apt-get -qq -y install libgoogle-perftools-dev libpcre3-dev libprotobuf-dev &&
        apt-get -qq -y install protobuf-compiler python3-pip unzip wget
    win:
      ''
  scripts:
    build:
      linux:
        'regression-tests/linux-opt-build.sh'
      win:
        'regression-tests/win-opt-build.sh'
    package:
      linux:
        ''
      win:
        ''
