system:
  username: 'build-user'
  homedir:
    linux: '/home/build-user'
    win: '/c/builds/tc-workdir'
  system_setup:
    linux:
      >
        apt-get -qq update &&
        apt-get -qq -y install git &&
        apt-get -qq -y install cmake3 &&
        apt-get -qq -y install build-essential &&
        apt-get -qq -y install libboost-all-dev &&
        apt-get -qq -y install libprotobuf8 &&
        apt-get -qq -y install protobuf-compiler &&
        apt-get -qq -y install libprotobuf-dev &&
        apt-get -qq -y install openssl &&
        apt-get -qq -y install libssl-dev &&
        apt-get -qq -y install libgoogle-perftools-dev
    win:
      ''
  scripts:
    build:
      linux:
        'regression-tests/linux-opt-build.sh'
      win:
        'regression-tests/win-opt-build.sh'
    package:
      linux:
        ''
      win:
        ''
